version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing deps...
      - curl -s -o mime.types "https://svn.apache.org/viewvc/httpd/httpd/trunk/docs/conf/mime.types?view=co"
      - mv mime.types /etc/
      - npm i -g yarn
      - yarn
  build:
    commands:
      - echo Building website...
      - yarn build
artifacts:
  files:
    - '**/*'
  base-directory: dist
