version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing deps...
      - npm i -g yarn
      - yarn
  build:
    commands:
      - echo Building website...
      - yarn build
artifacts:
  files:
    - '**/*'
  base-directory: dist
